# Generated by Django 5.x on 2026-08-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate", models.CharField(max_length=10, unique=True)),
                ("brand", models.CharField(max_length=40)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicles",
            },
        ),
        migrations.CreateModel(
            name="Rentals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=120)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "RESERVED"),
                            ("ACTIVE", "ACTIVE"),
                            ("CLOSED", "CLOSED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="RESERVED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        db_column="vehicle_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rentals",
                        to="gestion.vehicles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental",
                "verbose_name_plural": "Rentals",
                "db_table": "rentals",
            },
        ),
    ]
